"""init

Revision ID: 864f580e249b
Revises: 
Create Date: 2025-09-12 15:53:34.679119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864f580e249b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_domain_sources_id'), 'domain_sources', ['id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('bids', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('domain_created_at', sa.DateTime(), nullable=True),
    sa.Column('auction_ended_at', sa.DateTime(), nullable=False),
    sa.Column('domain_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_source_id'], ['domain_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)

    op.execute("""
        INSERT INTO domain_sources (name) VALUES 
        ('auctions_go_daddy'),
        ('expired_domains')
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_domain_sources_id'), table_name='domain_sources')
    op.drop_table('domain_sources')
    # ### end Alembic commands ###
